name: CD

on:
  workflow_run:
    workflows: ["CI"] # workflow's name from ci.yml
    types: [completed]
    branches: [feature/cicd]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: "render.com"  # GitHub environment for the secrets
    steps:
    -
      name: Debug Environment
      run: |
        echo "Using environment: ${{ github.environment }}"
        echo "DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}"    
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"    
    - 
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/awd-nestjs:latest

